// GENERATED CODE - DO NOT MODIFY BY HAND

import 'themes/a11y_dark.dart';
import 'themes/a11y_light.dart';
import 'themes/agate.dart';
import 'themes/an_old_hope.dart';
import 'themes/androidstudio.dart';
import 'themes/arduino_light.dart';
import 'themes/arta.dart';
import 'themes/ascetic.dart';
import 'themes/atelier_cave_dark.dart';
import 'themes/atelier_cave_light.dart';
import 'themes/atelier_dune_dark.dart';
import 'themes/atelier_dune_light.dart';
import 'themes/atelier_estuary_dark.dart';
import 'themes/atelier_estuary_light.dart';
import 'themes/atelier_forest_dark.dart';
import 'themes/atelier_forest_light.dart';
import 'themes/atelier_heath_dark.dart';
import 'themes/atelier_heath_light.dart';
import 'themes/atelier_lakeside_dark.dart';
import 'themes/atelier_lakeside_light.dart';
import 'themes/atelier_plateau_dark.dart';
import 'themes/atelier_plateau_light.dart';
import 'themes/atelier_savanna_dark.dart';
import 'themes/atelier_savanna_light.dart';
import 'themes/atelier_seaside_dark.dart';
import 'themes/atelier_seaside_light.dart';
import 'themes/atelier_sulphurpool_dark.dart';
import 'themes/atelier_sulphurpool_light.dart';
import 'themes/atom_one_dark_reasonable.dart';
import 'themes/atom_one_dark.dart';
import 'themes/atom_one_light.dart';
import 'themes/brown_paper.dart';
import 'themes/codepen_embed.dart';
import 'themes/color_brewer.dart';
import 'themes/darcula.dart';
import 'themes/dark.dart';
import 'themes/default.dart';
import 'themes/docco.dart';
import 'themes/dracula.dart';
import 'themes/far.dart';
import 'themes/foundation.dart';
import 'themes/github_gist.dart';
import 'themes/github.dart';
import 'themes/gml.dart';
import 'themes/googlecode.dart';
import 'themes/gradient_dark.dart';
import 'themes/grayscale.dart';
import 'themes/gruvbox_dark.dart';
import 'themes/gruvbox_light.dart';
import 'themes/hopscotch.dart';
import 'themes/hybrid.dart';
import 'themes/idea.dart';
import 'themes/ir_black.dart';
import 'themes/isbl_editor_dark.dart';
import 'themes/isbl_editor_light.dart';
import 'themes/kimbie.dark.dart';
import 'themes/kimbie.light.dart';
import 'themes/lightfair.dart';
import 'themes/magula.dart';
import 'themes/mono_blue.dart';
import 'themes/monokai_sublime.dart';
import 'themes/monokai.dart';
import 'themes/night_owl.dart';
import 'themes/nord.dart';
import 'themes/obsidian.dart';
import 'themes/ocean.dart';
import 'themes/paraiso_dark.dart';
import 'themes/paraiso_light.dart';
import 'themes/pojoaque.dart';
import 'themes/purebasic.dart';
import 'themes/qtcreator_dark.dart';
import 'themes/qtcreator_light.dart';
import 'themes/railscasts.dart';
import 'themes/rainbow.dart';
import 'themes/routeros.dart';
import 'themes/school_book.dart';
import 'themes/shades_of_purple.dart';
import 'themes/solarized_dark.dart';
import 'themes/solarized_light.dart';
import 'themes/sunburst.dart';
import 'themes/tomorrow_night_blue.dart';
import 'themes/tomorrow_night_bright.dart';
import 'themes/tomorrow_night_eighties.dart';
import 'themes/tomorrow_night.dart';
import 'themes/tomorrow.dart';
import 'themes/vs.dart';
import 'themes/vs2015.dart';
import 'themes/xcode.dart';
import 'themes/xt256.dart';
import 'themes/zenburn.dart';

const themeMap = {
  'a11y-dark': a11yDarkTheme,
  'a11y-light': a11yLightTheme,
  'agate': agateTheme,
  'an-old-hope': anOldHopeTheme,
  'androidstudio': androidstudioTheme,
  'arduino-light': arduinoLightTheme,
  'arta': artaTheme,
  'ascetic': asceticTheme,
  'atelier-cave-dark': atelierCaveDarkTheme,
  'atelier-cave-light': atelierCaveLightTheme,
  'atelier-dune-dark': atelierDuneDarkTheme,
  'atelier-dune-light': atelierDuneLightTheme,
  'atelier-estuary-dark': atelierEstuaryDarkTheme,
  'atelier-estuary-light': atelierEstuaryLightTheme,
  'atelier-forest-dark': atelierForestDarkTheme,
  'atelier-forest-light': atelierForestLightTheme,
  'atelier-heath-dark': atelierHeathDarkTheme,
  'atelier-heath-light': atelierHeathLightTheme,
  'atelier-lakeside-dark': atelierLakesideDarkTheme,
  'atelier-lakeside-light': atelierLakesideLightTheme,
  'atelier-plateau-dark': atelierPlateauDarkTheme,
  'atelier-plateau-light': atelierPlateauLightTheme,
  'atelier-savanna-dark': atelierSavannaDarkTheme,
  'atelier-savanna-light': atelierSavannaLightTheme,
  'atelier-seaside-dark': atelierSeasideDarkTheme,
  'atelier-seaside-light': atelierSeasideLightTheme,
  'atelier-sulphurpool-dark': atelierSulphurpoolDarkTheme,
  'atelier-sulphurpool-light': atelierSulphurpoolLightTheme,
  'atom-one-dark-reasonable': atomOneDarkReasonableTheme,
  'atom-one-dark': atomOneDarkTheme,
  'atom-one-light': atomOneLightTheme,
  'brown-paper': brownPaperTheme,
  'codepen-embed': codepenEmbedTheme,
  'color-brewer': colorBrewerTheme,
  'darcula': darculaTheme,
  'dark': darkTheme,
  'default': defaultTheme,
  'docco': doccoTheme,
  'dracula': draculaTheme,
  'far': farTheme,
  'foundation': foundationTheme,
  'github-gist': githubGistTheme,
  'github': githubTheme,
  'gml': gmlTheme,
  'googlecode': googlecodeTheme,
  'gradient-dark': gradientDarkTheme,
  'grayscale': grayscaleTheme,
  'gruvbox-dark': gruvboxDarkTheme,
  'gruvbox-light': gruvboxLightTheme,
  'hopscotch': hopscotchTheme,
  'hybrid': hybridTheme,
  'idea': ideaTheme,
  'ir-black': irBlackTheme,
  'isbl-editor-dark': isblEditorDarkTheme,
  'isbl-editor-light': isblEditorLightTheme,
  'kimbie.dark': kimbieDarkTheme,
  'kimbie.light': kimbieLightTheme,
  'lightfair': lightfairTheme,
  'magula': magulaTheme,
  'mono-blue': monoBlueTheme,
  'monokai-sublime': monokaiSublimeTheme,
  'monokai': monokaiTheme,
  'night-owl': nightOwlTheme,
  'nord': nordTheme,
  'obsidian': obsidianTheme,
  'ocean': oceanTheme,
  'paraiso-dark': paraisoDarkTheme,
  'paraiso-light': paraisoLightTheme,
  'pojoaque': pojoaqueTheme,
  'purebasic': purebasicTheme,
  'qtcreator_dark': qtcreatorDarkTheme,
  'qtcreator_light': qtcreatorLightTheme,
  'railscasts': railscastsTheme,
  'rainbow': rainbowTheme,
  'routeros': routerosTheme,
  'school-book': schoolBookTheme,
  'shades-of-purple': shadesOfPurpleTheme,
  'solarized-dark': solarizedDarkTheme,
  'solarized-light': solarizedLightTheme,
  'sunburst': sunburstTheme,
  'tomorrow-night-blue': tomorrowNightBlueTheme,
  'tomorrow-night-bright': tomorrowNightBrightTheme,
  'tomorrow-night-eighties': tomorrowNightEightiesTheme,
  'tomorrow-night': tomorrowNightTheme,
  'tomorrow': tomorrowTheme,
  'vs': vsTheme,
  'vs2015': vs2015Theme,
  'xcode': xcodeTheme,
  'xt256': xt256Theme,
  'zenburn': zenburnTheme,
};
